In [16]:
import sys
!{sys.executable} -m pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.4 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [1]:
# Covariance:

In [6]:
# Covariance Formula:
# cov(x, y) = Σ (x - x_mean) × (y - y_mean) / (n - 1)

In [5]:
import numpy as np

size =  [1000, 1500, 2000]
price = [200,  300,  400]

# Manual calculation
x_mean = sum(size) / len(size)
y_mean = sum(price) / len(price)

cov_manual = sum((x - x_mean) * (y - y_mean) 
             for x, y in zip(size, price)) / (len(size) - 1)

print(f"Manual covariance: {cov_manual}")

# Numpy verification
cov_numpy = np.cov(size, price)[0][1]
print(f"Numpy covariance:  {cov_numpy}")
print(f"Match: {cov_manual == cov_numpy} ")

Manual covariance: 50000.0
Numpy covariance:  50000.0
Match: True 


In [17]:
# Numpy dot product
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 6],
              [7, 1]])

result = np.dot(A, B)

# print(f"Matrix A:\n{A}")
# print(f"\nMatrix B:\n{B}")
print(f"\nDot Product A × B:\n{result}")


Dot Product A × B:
[[16  8]
 [34 22]]


In [18]:

# Manual dot product

# Matrix A
A = [[1, 2],
     [3, 4]]

# Matrix B
B = [[5, 6],
     [7, 8]]

# Result matrix (start with zeros)
result = [[0, 0],
          [0, 0]]

# Calculate dot product manually
for i in range(2):        # rows of A
    for j in range(2):    # columns of B
        for k in range(2): # multiply and add
            result[i][j] += A[i][k] * B[k][j]

print("Result:")
for row in result:
    print(row)

Result:
[19, 22]
[43, 50]


In [19]:

# PCA
import numpy as np

# Simple house dataset
data = np.array([[1000, 3],
                 [1500, 4],
                 [2000, 5]])

In [20]:

print("Original data (3 houses, 2 features):")
print(data)

Original data (3 houses, 2 features):
[[1000    3]
 [1500    4]
 [2000    5]]


In [21]:
# Step 1 - Mean center the data
mean = np.mean(data, axis=0)
centered = data - mean
print(f"\nMean: {mean}")
print(f"Centered data:\n{centered}")



Mean: [1500.    4.]
Centered data:
[[-500.   -1.]
 [   0.    0.]
 [ 500.    1.]]


In [22]:

# Step 2 - Covariance matrix
cov_matrix = np.cov(centered.T)
print(f"\nCovariance matrix:\n{cov_matrix}")




Covariance matrix:
[[2.5e+05 5.0e+02]
 [5.0e+02 1.0e+00]]


In [23]:

# Step 3 - Find Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print(f"\nEigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")



Eigenvalues: [ 2.50001000e+05 -2.08166817e-17]
Eigenvectors:
[[ 0.999998 -0.002   ]
 [ 0.002     0.999998]]


In [24]:

# Step 4 - Sort by importance (largest eigenvalue first)
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print(f"\nSorted Eigenvalues: {eigenvalues}")



Sorted Eigenvalues: [ 2.50001000e+05 -2.08166817e-17]


In [25]:

# Step 5 - Keep only top 1 component
top_eigenvector = eigenvectors[:, 0]
print(f"\nMost important direction: {top_eigenvector}")




Most important direction: [0.999998 0.002   ]


In [26]:

# Step 6 - Transform data
reduced = centered.dot(top_eigenvector)
print(f"\nReduced data (2 features → 1 feature):")
for i, val in enumerate(reduced):
    print(f"House {i+1}: {val:.2f}")


Reduced data (2 features → 1 feature):
House 1: -500.00
House 2: 0.00
House 3: 500.00
