# Linear Algebra for Machine Learning
> Complete guide with theory, math and code examples

## 1. Vectors
A vector is an arrow with:
- **Direction** → which way it points
- **Magnitude** → how long it is

Vector **(3, 2)** means:
- Move 3 steps right
- Move 2 steps up

In [ ]:
import numpy as np

# Define a vector

v = np.array([3, 2])
print(f"Vector: {v}")
print(f"Direction: {v}")
print(f"Magnitude: {np.linalg.norm(v):.2f}")

Vector: [3 2]
Direction: [3 2]
Magnitude: 3.61


## 2. Vector Coordinates
Coordinates are just **how many steps in each direction**

**(x, y) = how far right, how far up**

In [ ]:
# Vector coordinates
v = np.array([4, 3])
print(f"x coordinate (right): {v[0]}")

print(f"y coordinate (up): {v[1]}")

x coordinate (right): 4
y coordinate (up): 3


## 3. Basis Vectors
Basis vectors are the **simplest, purest directions** in a space.

- **î = (1, 0)** → one pure step RIGHT
- **ĵ = (0, 1)** → one pure step UP

Every vector is just a combination of basis vectors:
> **(4, 3) = 4î + 3ĵ**

In [4]:
# Basis vectors
i_hat = np.array([1, 0])  # right
j_hat = np.array([0, 1])  # up

# Any vector = scaled combination of basis vectors
v = 4 * i_hat + 3 * j_hat
print(f"4î + 3ĵ = {v}")

4î + 3ĵ = [4 3]


## 4. Linear Combination
> **Scale vectors + Add them together**

Anytime you multiply vectors by numbers and add them = Linear Combination

In [5]:
# Linear combination
a = np.array([2, 1])
b = np.array([1, 3])

# 5a + 2b
result = 5 * a + 2 * b
print(f"a = {a}")
print(f"b = {b}")
print(f"5a + 2b = {result}")

a = [2 1]
b = [1 3]
5a + 2b = [12 11]


## 5. Span
> **Span = ALL points you can possibly reach using linear combinations**

- Two different directions → span = whole 2D space
- Two same directions → span = just a line

In [6]:
# Two different directions = span whole space
v1 = np.array([1, 0])  # right
v2 = np.array([0, 1])  # up
print("v1 and v2 point in different directions")
print(f"They span the whole 2D space")

print()

# Two same directions = span only a line
v3 = np.array([1, 0])  # right
v4 = np.array([2, 0])  # also right
print("v3 and v4 point in SAME direction")
print(f"They only span a line")

v1 and v2 point in different directions
They span the whole 2D space

v3 and v4 point in SAME direction
They only span a line


## 6. Linear Independence
> **Does each vector add a NEW direction?**

- **Independent** → each vector is truly different 
- **Dependent** → one vector is just a copy of another 

In ML: dependent vectors = **redundant features**

In [16]:
# Check linear independence using determinant
# Independent vectors
A = np.array([[1, 0],
              [0, 1]])
print(f"Independent vectors determinant: {np.linalg.det(A):.2f} (not zero)")

# Dependent vectors
B = np.array([[1, 0],
              [2, 0]])
print(f"Dependent vectors determinant: {np.linalg.det(B):.2f} (zero)")

Independent vectors determinant: 1.00 (not zero)
Dependent vectors determinant: 0.00 (zero)


## 7. Matrices
> **A matrix is a transformation machine**

It takes a vector and stretches, rotates, or flips it.

```
vector goes in → | MATRIX | → new vector comes out
```

In [8]:
# Matrix transformation
matrix = np.array([[2, 0],
                   [0, 2]])

vector = np.array([1, 0])

result = np.dot(matrix, vector)
print(f"Vector before: {vector}")
print(f"Matrix:\n{matrix}")
print(f"Vector after: {result}  ← stretched by 2!")

Vector before: [1 0]
Matrix:
[[2 0]
 [0 2]]
Vector after: [2 0]  ← stretched by 2!


## 8. Identity Matrix
> **A machine that does NOTHING**

Whatever you pass through it comes out exactly the same.

In [9]:
# Identity matrix
I = np.eye(2)
print(f"Identity matrix:\n{I}")

v = np.array([5, 3])
result = np.dot(I, v)
print(f"\nVector in: {v}")
print(f"Vector out: {result}  ← unchanged!")

Identity matrix:
[[1. 0.]
 [0. 1.]]

Vector in: [5 3]
Vector out: [5. 3.]  ← unchanged!


## 9. Transpose Matrix
> **Flip the matrix — rows become columns, columns become rows**

Used in ML to make matrix shapes compatible for multiplication.

In [10]:
# Transpose
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(f"Original matrix (2x3):\n{A}")
print(f"\nTransposed matrix (3x2):\n{A.T}")

Original matrix (2x3):
[[1 2 3]
 [4 5 6]]

Transposed matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]


## 10. Determinant
> **Tells you how much UNIQUE information your features contain**

| Determinant | Meaning |
|---|---|
| Zero | Features are redundant — model breaks |
| Not zero | Features are unique — model learns well |

In [11]:
# Determinant example
# Bad features (sqft and meters — same thing!)
bad = np.array([[1000, 92.9],
                [1500, 139.4]])
print(f"Bad features determinant: {np.linalg.det(bad):.4f} ← near zero!")

# Good features (size and rooms — different!)
good = np.array([[1000, 3],
                 [1500, 4]])
print(f"Good features determinant: {np.linalg.det(good):.4f} ← not zero!")

Bad features determinant: 50.0000 ← near zero!
Good features determinant: -500.0000 ← not zero!


## 11. Inverse Matrix
> **The matrix that UNDOES what the original matrix did**

- Matrix = forward machine
- Inverse = reverse machine

Only exists when determinant is NOT zero!

In [12]:
# Inverse matrix
A = np.array([[2, 1],
              [1, 3]])

det = np.linalg.det(A)
print(f"Matrix:\n{A}")
print(f"Determinant: {det:.2f}")

if abs(det) > 1e-10:
    inv = np.linalg.inv(A)
    print(f"\nInverse:\n{inv}")
    print(f"\nVerification A × A_inv (should be identity):\n{np.round(A @ inv)}")
else:
    print("Inverse does NOT exist!")

Matrix:
[[2 1]
 [1 3]]
Determinant: 5.00

Inverse:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Verification A × A_inv (should be identity):
[[ 1.  0.]
 [-0.  1.]]


## 12. Dot Product
> **How similar are two vectors?**

Multiply matching numbers and add them up.

| Result | Meaning |
|---|---|
| Large number | Vectors very similar |
| Zero | Vectors completely different |
| Negative | Vectors opposite directions |

In [13]:
# Dot product — vectors
a = np.array([2, 3])
b = np.array([4, 1])
print(f"a = {a}")
print(f"b = {b}")
print(f"Dot product: {np.dot(a, b)}")

print()

# Dot product — matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"A × B:\n{np.dot(A, B)}")

a = [2 3]
b = [4 1]
Dot product: 11

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
A × B:
[[19 22]
 [43 50]]


## 13. Eigenvalues & Eigenvectors
> **A × v = λ × v**

- **Eigenvector (v)** = direction that survives transformation (no rotation, just stretching)
- **Eigenvalue (λ)** = how much it got stretched

Used in **PCA** to find most important directions in data.

In [14]:
# Eigenvalues & Eigenvectors
A = np.array([[3, 0],
              [0, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Matrix:\n{A}")
print(f"\nEigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")
print("\n→ Eigenvalue 3 means direction (1,0) gets stretched by 3")
print("→ Eigenvalue 2 means direction (0,1) gets stretched by 2")

Matrix:
[[3 0]
 [0 2]]

Eigenvalues: [3. 2.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]

→ Eigenvalue 3 means direction (1,0) gets stretched by 3
→ Eigenvalue 2 means direction (0,1) gets stretched by 2


## 14. PCA using Eigenvalues (Full Example)
> Reduce 2 features → 1 feature while keeping most important information

In [15]:
# PCA from scratch using eigenvalues
data = np.array([[1000, 3],
                 [1500, 4],
                 [2000, 5]])

# Step 1 - Mean center
mean = np.mean(data, axis=0)
centered = data - mean
print(f"Step 1 - Centered data:\n{centered}")

# Step 2 - Covariance matrix
cov = np.cov(centered.T)
print(f"\nStep 2 - Covariance matrix:\n{cov}")

# Step 3 - Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov)
print(f"\nStep 3 - Eigenvalues: {eigenvalues}")

# Step 4 - Sort by importance
idx = np.argsort(eigenvalues)[::-1]
eigenvectors = eigenvectors[:, idx]

# Step 5 - Reduce to 1 dimension
reduced = centered.dot(eigenvectors[:, 0])
print(f"\nStep 4 - Reduced data (2 features → 1):")
for i, val in enumerate(reduced):
    print(f"  House {i+1}: {val:.2f}")

Step 1 - Centered data:
[[-500.   -1.]
 [   0.    0.]
 [ 500.    1.]]

Step 2 - Covariance matrix:
[[2.5e+05 5.0e+02]
 [5.0e+02 1.0e+00]]

Step 3 - Eigenvalues: [ 2.50001000e+05 -2.08166817e-17]

Step 4 - Reduced data (2 features → 1):
  House 1: -500.00
  House 2: 0.00
  House 3: 500.00
