In [1]:
# Practical Use Case — Image Compression

In [ ]:
# The Idea:

# Use SVD to compress an image by keeping only the most important singular values

In [ ]:
# Why images?

# An image is just a matrix of numbers (pixel values)
# SVD finds the most important patterns in those pixels
# Keep top patterns → smaller file, similar quality

In [4]:
pip install matplotlib

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 7.4 MB/s eta 0:00:00a 0:00:01m
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 27.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 4.6 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
import matplotlib.pyplot as plt


Matplotlib is building the font cache; this may take a moment.


In [6]:
# Step 1 - Create a simple image (matrix of numbers)
# WHY: Image is just a matrix — perfect for SVD
image = np.array([
    [100, 100, 100, 200, 200, 200],
    [100, 100, 100, 200, 200, 200],
    [100, 100, 100, 200, 200, 200],
    [200, 200, 200, 100, 100, 100],
    [200, 200, 200, 100, 100, 100],
    [200, 200, 200, 100, 100, 100],
])

print(f"Original image matrix:\n{image}")
print(f"Original size: {image.shape}")


Original image matrix:
[[100 100 100 200 200 200]
 [100 100 100 200 200 200]
 [100 100 100 200 200 200]
 [200 200 200 100 100 100]
 [200 200 200 100 100 100]
 [200 200 200 100 100 100]]
Original size: (6, 6)


In [10]:

# Step 2 - Apply SVD
# WHY: Break image into U, Σ, V^T
U , sigma, VT = np.linalg.svd(image)
print(f"\nSingular values: {sigma}")
print("↑ Bigger = more important pattern")


Singular values: [9.00000000e+02 3.00000000e+02 9.21237651e-14 9.63836029e-15
 2.20723790e-46 1.17398003e-78]
↑ Bigger = more important pattern


In [15]:
print(f"\nLeft Singular values: {U}")


Left Singular values: [[-4.08248290e-01 -4.08248290e-01  7.48487245e-01 -3.26241493e-01
   0.00000000e+00  0.00000000e+00]
 [-4.08248290e-01 -4.08248290e-01 -6.56777043e-01 -4.85088222e-01
   0.00000000e+00 -2.01869717e-18]
 [-4.08248290e-01 -4.08248290e-01 -9.17102019e-02  8.11329714e-01
  -5.71300471e-17 -5.87429669e-19]
 [-4.08248290e-01  4.08248290e-01 -3.48959869e-17 -9.94162273e-17
   8.16496581e-01 -8.68876303e-17]
 [-4.08248290e-01  4.08248290e-01 -3.48959869e-17  1.16060752e-17
  -4.08248290e-01 -7.07106781e-01]
 [-4.08248290e-01  4.08248290e-01 -3.48959869e-17  1.16060752e-17
  -4.08248290e-01  7.07106781e-01]]


In [17]:
print(f"\nRight Singular values: {VT}")


Right Singular values: [[-4.08248290e-01 -4.08248290e-01 -4.08248290e-01 -4.08248290e-01
  -4.08248290e-01 -4.08248290e-01]
 [ 4.08248290e-01  4.08248290e-01  4.08248290e-01 -4.08248290e-01
  -4.08248290e-01 -4.08248290e-01]
 [-8.02430513e-01  5.31901729e-01  2.70528783e-01 -4.23584978e-17
  -4.23584978e-17 -4.23584978e-17]
 [ 1.50903741e-01  6.19473338e-01 -7.70377079e-01 -4.12048591e-17
   6.98174434e-17  6.98174434e-17]
 [ 0.00000000e+00 -2.10168858e-16  1.82389381e-16  8.16496581e-01
  -4.08248290e-01 -4.08248290e-01]
 [ 0.00000000e+00  1.00290288e-17  6.05340845e-18  2.13979392e-17
  -7.07106781e-01  7.07106781e-01]]


In [12]:
# Step 3 - Reconstruct with only TOP 1 singular value
# WHY: Keep only most important pattern — throw rest away
k = 1
compressed = sigma[0] * np.outer(U[:, 0], VT[0, :])
print(f"\nCompressed image (using only top {k} singular value):")
print(np.round(compressed))


Compressed image (using only top 1 singular value):
[[150. 150. 150. 150. 150. 150.]
 [150. 150. 150. 150. 150. 150.]
 [150. 150. 150. 150. 150. 150.]
 [150. 150. 150. 150. 150. 150.]
 [150. 150. 150. 150. 150. 150.]
 [150. 150. 150. 150. 150. 150.]]


In [13]:
# Step 4 - Check how close it is to original
error = np.round(np.linalg.norm(image - compressed), 2)
print(f"\nError from original: {error}")
print("Lower error = better compression ")


Error from original: 300.0
Lower error = better compression 


In [14]:
# Step 5 - Try with top 2 singular values
k = 2
compressed2 = sum(sigma[i] * np.outer(U[:, i], VT[i, :]) for i in range(k))
error2 = np.round(np.linalg.norm(image - compressed2), 2)
print(f"\nWith top 2 singular values — Error: {error2}")
print("Even closer to original! ")


With top 2 singular values — Error: 0.0
Even closer to original! 


In [ ]:
# Original matrix
#       ↓
# np.linalg.svd() → U, Σ, V^T
#       ↓
# Choose k (how many patterns to keep)
#       ↓
# Reconstruct with only top k
#       ↓
# Compressed version 

In [ ]:
# For m*n Matrix

In [18]:
import numpy as np

# Original matrix (4x5) — imagine this is any dataset
A = np.array([
    [1,  2,  3,  4,  5],
    [2,  4,  6,  8,  10],
    [3,  6,  9,  12, 15],
    [4,  8,  12, 16, 20]
])

In [20]:
print(f"Original matrix ({A.shape[0]}x{A.shape[1]}):")
print(A)

Original matrix (4x5):
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]]


In [ ]:
# Step 1 - Apply SVD
U, sigma, VT = np.linalg.svd(A)
print(f"\nSingular values: {np.round(sigma, 2)}")
print("↑ See how first value is huge, rest are basically zero!")


Singular values: [40.62  0.    0.    0.  ]
↑ See how first value is huge, rest are basically zero!


In [22]:
# Step 2 - Keep only top k=1
k = 1
compressed = sum(sigma[i] * np.outer(U[:, i], VT[i, :]) for i in range(k))
print(f"\nCompressed matrix (k={k}):")
print(np.round(compressed, 1))


Compressed matrix (k=1):
[[ 1.  2.  3.  4.  5.]
 [ 2.  4.  6.  8. 10.]
 [ 3.  6.  9. 12. 15.]
 [ 4.  8. 12. 16. 20.]]


In [23]:
# Step 3 - Check error
error = np.round(np.linalg.norm(A - compressed), 4)
print(f"\nError: {error}")


Error: 0.0


In [24]:
# Step 4 - How much data did we save?
original_size = A.shape[0] * A.shape[1]
compressed_size = k * (A.shape[0] + A.shape[1] + 1)
print(f"\nOriginal size: {original_size} numbers")
print(f"Compressed size: {compressed_size} numbers")
print(f"Saved: {original_size - compressed_size} numbers! ")


Original size: 20 numbers
Compressed size: 10 numbers
Saved: 10 numbers! 


In [ ]:
# PCA:

# A technique to reduce dimensions
# Goal → find most important directions in data
# Steps → center data → covariance matrix → eigenvalues → done

# SVD:

# A math tool that breaks any matrix into 3 parts
# Goal → decompose any matrix into U, Σ, V^T
# Works on any matrix directly